merge mvp branch into develop
mayarafoliveira/empresas pull request #2
Opened 2021-07-26 18:28 UTC by mayarafoliveira

2021-07-26 18:50 UTC, brennobemoura requested changes
Deixei apenas umas recomendações para ficar melhor a escrita. Só um que é sobre o uso indevido da atribuição em uma lazy var nos detalhes. Ficou top a refatoração!!

2021-07-26 18:50 UTC, brennobemoura commented on Empresas/Controller/EnterpriseDetailViewController.swift
> +    private lazy var enterpriseDetailView = EnterpriseDetailView(enterprise: nil)
Aqui vc pode usar o enterprise msm, pq ele já vai estar atribuído no init

2021-07-26 18:50 UTC, brennobemoura commented on Empresas/Controller/EnterpriseDetailViewController.swift
> +        self.enterpriseDetailView = EnterpriseDetailView(enterprise: self.enterprise)
E aqui vc pode tirar essa linha, pq fica repetido. O lazy var vai instanciar a variável enterpriseDetailView só no momento que for chamada, e isso faz com que a variável tenha acesso as propriedades da view controller atualizadas

2021-07-26 18:50 UTC, brennobemoura commented on Empresas/View/LoginView.swift
>          guard let passwordText = passwordTextField.text else { return }
Aqui vc pode escrever assim:

```swift
guard
    let emailText = emailTextField.text,
    let passwordText = passwordTextField.text
else { return }
```

2021-07-26 18:50 UTC, brennobemoura commented on Empresas/System Delegate/SceneDelegate.swift
> +//        window?.rootViewController = searchViewController
E esses comentários? Seria bom remover

2021-07-26 19:04 UTC, mayarafoliveira commented on Empresas/System Delegate/SceneDelegate.swift
> +//        window?.rootViewController = searchViewController
Verdaade, esqueci de remover

2021-07-26 19:09 UTC, mayarafoliveira commented
> Deixei apenas umas recomendações para ficar melhor a escrita. Só um que é sobre o uso indevido da atribuição em uma lazy var nos detalhes. Ficou top a refatoração!!

Obg!! Faz muito sentido essas recomendações, vou corrigir lá.

2021-07-27 13:42 UTC, o-nnerb approved these changes

2021-07-27 14:25 UTC, merged